# Serverless Config
service:
  name: celo-network-monitor

# Plugins
plugins:
  - serverless-webpack

# Provider
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30

  # Environment Variables
  environment:
    # TODO: Place env vars here

# Functions
functions:
  monitor:
    handler: handler.monitor
    reservedConcurrency: 1
    events:
      - schedule: rate(5 minutes)

